### ISSUE TITLE
Add a spec update method that will add the spec changes to the spec diff annotation and also to the ingress spec

### ISSUE THREAD

**Issue by maleck13** [kcp-dev/kcp-glbc#364]
Add a method within the ingress package that will allow us to encapsulate the udpdates we make to the spec of an ingress. This method should add the  update to the spec diif annotation ```ClusterSpecDiffAnnotationPrefix``` but also currently add the change to the ingress spec. The main changes we make to spec currently are
- replacing /adding the host(s) in the ingress
- replacing/adding the tls section

- [x] New method(s) in place and any update the ingress spec done via that method
- [ ] E2e tests updated to expect the annotation to be set
- [ ] Unit tests in place for new method
