### ISSUE TITLE
Performance Testing - Load & Stress testing foundations

### ISSUE THREAD

**Issue by david-martin** [kcp-dev/kcp-glbc#440]
* [ ] Define a base performance benchmark - run via Github Actions as a 'happy path' on-demand e.g. pre release testing
* [ ] Set up a load test script & CI job, building on the base performance test, that executes configurable load levels mimicking expected usage.
* [ ] Set up a stress test script & CI job, building on the base performance test, that executes configurable high stress loads over short periods of time, mimicking expected spikes in usage

Notes:
The round trip time to LE and AWS will affect rampup and concurrency. We'll need to be aware of below when setting up the test parameters:
* [Quotas - Amazon Route 53](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/DNSLimitations.html)
* [Staging Environment - Let's Encrypt](https://letsencrypt.org/docs/staging-environment/#:~:text=Rate%20Limits,-The%20staging%20environment&text=The%20Certificates%20per%20Registered%20Domain,3%20hour%20period%20per%20IP)

The base performance benchmark can start as 50 workspaces (e.g. 50 users), with 10 ingresses per workspace.
Each user will create 1 new ingress per minute.

The indicator for ingress admission, as defined in https://github.com/kcp-dev/kcp-glbc/blob/main/docs/observability/service_level_indicators_and_objectives.adoc should be the primary measure of performance.

As this Epic is establishing a foundation, there is some scope for experimenting with how best to report the test results, and comparing the results with the expected baseline values (which need to be established first).
Visual elements could be captured, or linked to in grafana with time range params to filter to the time leading up to the test, during and after.
Dashboards and panels can be modified or extended to help with visualising the most important data.

This Epic can be considered done when the main 3 tasks are done, and can be run on-demand or hooked into existing CI & CD flows.

**Comment by maleck13** [comment]
I think we an use the resource status to measure performance soon. We don't create reconcile the DNS until the certificate is ready and we wont update the status of the ingress until we have checked the DNS has propigated. So we can likely use the appearance of our dns name  in the status block as the ingress being ready https://github.com/kcp-dev/kcp-glbc/issues/354
