### ISSUE TITLE
GLBC standalone

### ISSUE THREAD

**Issue by maleck13** [kcp-dev/kcp-glbc#521]
## Issue Description
Not all users will be using the KCP workload service. Multi-cluster ingress and traffic management is valuable in many different multi-cluster setups. This issue captures investigations and concepts around providing GLBC standalone.  

### Use Cases
Use cases remain the same
- Provide a secure host for north/south access to workloads 
- Traffic Shaping APIs with sane defaults 
- Automatic DNS support for Ingress/OpenShift Route and Gateway API
- CustomDomain verification for multi-tenant clusters

### Overview
Provide a separate control plane that offers multi-cluster integration, visibility and control over north/south ingress while still being able to use standard API such as Ingress, OpenShift Route and HTTPRoute.  Provide and integration with these APIs that works standalone, that is compatible with gitops and with KCP. As much as possible support existing tooling and flows such as (argo and kubectl).

### Investigations

- [ ] Externalising the internal traffic object as the non kcp representation of Ingress objects
- [ ] Validating Custom Domains via admission webhook
- [ ] Using managed fields to indicate to ArgoCD we are managing certain fields of the ingress object
- [ ] Ingress Cluster registration with the control plane
- [ ] Syncing Ingress state from data plane clusters to GLBC 
- [ ] Transforming ingress state based on control plane traffic objects
